/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import java.awt.CardLayout;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vivek
 */
public class TreatmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    private Statement statement;
    private JPanel userProcessContainer;
    private long pId;
    private String appointmentId ;
     private Connection connection;

    public TreatmentPanel(Statement statement, JPanel userProcessContainer, Connection connection, String appointmentId) throws SQLException {
        initComponents();
         this.statement = statement;
         this.connection = connection;
         this.appointmentId = appointmentId;
         this.userProcessContainer =userProcessContainer;
         DefaultTableModel model = (DefaultTableModel) treatmentCatalogueTable.getModel();
         
         
        String getTreatments = "select treatment_name ,treatment_cost from treatment_catalog";
        ResultSet rs = statement.executeQuery(getTreatments);
        while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString(1), 
                    rs.getString(2)
                });
            }
        
        toothComboBox.addItem(rs);

    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        treatmentCatalogueTable = new javax.swing.JTable();
        proceedButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nameSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        toothTreatmentField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        toothComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        medicineNameTextField = new javax.swing.JTextField();
        nameSeparator6 = new javax.swing.JSeparator();
        toothTypeCombobox = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        treatmentTable = new javax.swing.JTable();
        addTooth = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(55, 96, 128));
        setPreferredSize(new java.awt.Dimension(1100, 617));

        treatmentCatalogueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Treatment Name", "Treatment Cost"
            }
        ));
        treatmentCatalogueTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(treatmentCatalogueTable);

        proceedButton.setBackground(new java.awt.Color(171, 204, 67));
        proceedButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        proceedButton.setText("Proceed");
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(171, 204, 67));
        addButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(55, 96, 128));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel7.setText("Tooth Id");

        nameSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel8.setText("Treatment Details");

        toothTreatmentField.setBackground(new java.awt.Color(55, 96, 128));
        toothTreatmentField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setBackground(new java.awt.Color(55, 96, 128));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tooth Details");

        toothComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UL1", "UL2", "UL3", "UL4", "UL5", "UL6", "UL7", "UL8", "UR1", "UR2", "UR3", "UR4", "UR5", "UR6", "UR7", "UR8", "LL1", "LL2", "LL3", "LL4", "LL5", "LL6", "LL7", "LL8", "LR1", "LR2", "LR3", "LR4", "LR5", "LR6", "LR7", "LR8" }));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel9.setText("Tooth Type");

        medicineNameTextField.setBackground(new java.awt.Color(55, 96, 128));
        medicineNameTextField.setBorder(null);
        medicineNameTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        medicineNameTextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        medicineNameTextField.setOpaque(false);
        medicineNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                medicineNameTextFieldFocusGained(evt);
            }
        });
        medicineNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineNameTextFieldActionPerformed(evt);
            }
        });

        nameSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        toothTypeCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Incissor", "Canine", "Pre-Molar", "Molar" }));
        toothTypeCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toothTypeComboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toothComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(toothTypeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(medicineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toothTreatmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addComponent(jLabel7)
                .addGap(8, 8, 8)
                .addComponent(toothComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medicineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toothTypeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toothTreatmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        treatmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Treatment Name", "Treatment Cost"
            }
        ));
        jScrollPane3.setViewportView(treatmentTable);

        addTooth.setBackground(new java.awt.Color(171, 204, 67));
        addTooth.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        addTooth.setText("Add Tooth");
        addTooth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToothActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(23, 35, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Treatment Information");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(proceedButton, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(addTooth, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addTooth))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(addButton)
                                .addGap(61, 61, 61)
                                .addComponent(proceedButton)))
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
        // TODO add your handling code here:
        
       PrescriptionPanel presciption = null;
        try {
            presciption = new PrescriptionPanel(statement, userProcessContainer,connection,appointmentId);
        } catch (SQLException ex) {
            Logger.getLogger(TreatmentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        userProcessContainer.add("PrescriptionPanel", presciption);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
        
    }//GEN-LAST:event_proceedButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = treatmentCatalogueTable.getSelectedRow();
        
       if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select Treatmen to add" ,"Warning" , JOptionPane.WARNING_MESSAGE);
            return;
        } 
       
       String treatmentName =  treatmentCatalogueTable.getValueAt(selectedRow, 0).toString();
       String treatmentCost    =  treatmentCatalogueTable.getValueAt(selectedRow, 1).toString();
       
       DefaultTableModel model = (DefaultTableModel) treatmentTable.getModel();
        try {
            statement.executeUpdate("INSERT INTO treatment VALUES ('" 
                    + treatmentCost +"','" + appointmentId + "','"+ treatmentName + "')");
             model.addRow(new Object[]
       { treatmentName , 
         treatmentCost  });
       
       JOptionPane.showMessageDialog(null, "Treatment Details Added");
        } catch (SQLException ex) {
            Logger.getLogger(TreatmentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    
      
     
    }//GEN-LAST:event_addButtonActionPerformed

    private void medicineNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineNameTextFieldActionPerformed

    private void medicineNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_medicineNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineNameTextFieldFocusGained

    private void toothTypeComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toothTypeComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toothTypeComboboxActionPerformed

    private void addToothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToothActionPerformed
        try {
            // TODO add your handling code here:
            String toothType = toothTypeCombobox.getSelectedItem().toString();
            String toothID = toothComboBox.getSelectedItem().toString();
            String toothTreatment = toothTreatmentField.getText();
            
            
            CallableStatement stmt = null;
            
            stmt = connection.prepareCall("{call insertToothRow(?,?,?,?)}");
            
            stmt.setString(1, appointmentId);
            stmt.setString(2, toothID);
            stmt.setString(3, toothType);
            stmt.setString(4, toothTreatment);            
            
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Tooth Details Added");
        } catch (SQLException ex) {
            Logger.getLogger(TreatmentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addToothActionPerformed

    private void populateDefault() throws SQLException {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addTooth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField medicineNameTextField;
    private javax.swing.JSeparator nameSeparator4;
    private javax.swing.JSeparator nameSeparator6;
    private javax.swing.JButton proceedButton;
    private javax.swing.JComboBox toothComboBox;
    private javax.swing.JTextField toothTreatmentField;
    private javax.swing.JComboBox toothTypeCombobox;
    private javax.swing.JTable treatmentCatalogueTable;
    private javax.swing.JTable treatmentTable;
    // End of variables declaration//GEN-END:variables

}
